//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.8.1.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SettingsUpdated {
            get {
                return ((bool)(this["SettingsUpdated"]));
            }
            set {
                this["SettingsUpdated"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DEBUG")]
        public global::SRS.Utilities.LogLevel LogLevel {
            get {
                return ((global::SRS.Utilities.LogLevel)(this["LogLevel"]));
            }
            set {
                this["LogLevel"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ProgramData\\RIS\\")]
        public string WorkingFolder {
            get {
                return ((string)(this["WorkingFolder"]));
            }
            set {
                this["WorkingFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string AdminPassword {
            get {
                return ((string)(this["AdminPassword"]));
            }
            set {
                this["AdminPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string Decoder1_Server {
            get {
                return ((string)(this["Decoder1_Server"]));
            }
            set {
                this["Decoder1_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9300")]
        public int Decoder1_Port {
            get {
                return ((int)(this["Decoder1_Port"]));
            }
            set {
                this["Decoder1_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public int Vehicles_Rows {
            get {
                return ((int)(this["Vehicles_Rows"]));
            }
            set {
                this["Vehicles_Rows"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Vehicles_Columns {
            get {
                return ((int)(this["Vehicles_Columns"]));
            }
            set {
                this["Vehicles_Columns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("+++LIVE-Ticker+++  Der Text kann in den Optionen bearbeitet werden   +++LIVE-Tick" +
            "er+++")]
        public string Ticker_Text {
            get {
                return ((string)(this["Ticker_Text"]));
            }
            set {
                this["Ticker_Text"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Vehicles_AutoDisponieren {
            get {
                return ((bool)(this["Vehicles_AutoDisponieren"]));
            }
            set {
                this["Vehicles_AutoDisponieren"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Vehicles_Statusbox {
            get {
                return ((bool)(this["Vehicles_Statusbox"]));
            }
            set {
                this["Vehicles_Statusbox"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:30:00")]
        public global::System.TimeSpan Monitor_AlarmTime {
            get {
                return ((global::System.TimeSpan)(this["Monitor_AlarmTime"]));
            }
            set {
                this["Monitor_AlarmTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:15:00")]
        public global::System.TimeSpan Monitor_AlarmDelayTime {
            get {
                return ((global::System.TimeSpan)(this["Monitor_AlarmDelayTime"]));
            }
            set {
                this["Monitor_AlarmDelayTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan Monitor_WakeupStatusTime {
            get {
                return ((global::System.TimeSpan)(this["Monitor_WakeupStatusTime"]));
            }
            set {
                this["Monitor_WakeupStatusTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:05:00")]
        public global::System.TimeSpan Monitor_WakeupAlarmTime {
            get {
                return ((global::System.TimeSpan)(this["Monitor_WakeupAlarmTime"]));
            }
            set {
                this["Monitor_WakeupAlarmTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailOutput_Server {
            get {
                return ((string)(this["MailOutput_Server"]));
            }
            set {
                this["MailOutput_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MailOutput_Port {
            get {
                return ((int)(this["MailOutput_Port"]));
            }
            set {
                this["MailOutput_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MailOutput_SSL {
            get {
                return ((bool)(this["MailOutput_SSL"]));
            }
            set {
                this["MailOutput_SSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailOutput_User {
            get {
                return ((string)(this["MailOutput_User"]));
            }
            set {
                this["MailOutput_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailOutput_Password {
            get {
                return ((string)(this["MailOutput_Password"]));
            }
            set {
                this["MailOutput_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Rescue-Information-System")]
        public string MailOutput_Sender {
            get {
                return ((string)(this["MailOutput_Sender"]));
            }
            set {
                this["MailOutput_Sender"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Fax-Message-Service")]
        public string MailOutput_Subject {
            get {
                return ((string)(this["MailOutput_Subject"]));
            }
            set {
                this["MailOutput_Subject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailInput_Server {
            get {
                return ((string)(this["MailInput_Server"]));
            }
            set {
                this["MailInput_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MailInput_Port {
            get {
                return ((int)(this["MailInput_Port"]));
            }
            set {
                this["MailInput_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MailInput_SSL {
            get {
                return ((bool)(this["MailInput_SSL"]));
            }
            set {
                this["MailInput_SSL"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailInput_User {
            get {
                return ((string)(this["MailInput_User"]));
            }
            set {
                this["MailInput_User"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailInput_Password {
            get {
                return ((string)(this["MailInput_Password"]));
            }
            set {
                this["MailInput_Password"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string MailInput_Subject {
            get {
                return ((string)(this["MailInput_Subject"]));
            }
            set {
                this["MailInput_Subject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Alarm-Message-Service")]
        public string MailAms_Subject {
            get {
                return ((string)(this["MailAms_Subject"]));
            }
            set {
                this["MailAms_Subject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Route_Zip {
            get {
                return ((string)(this["Route_Zip"]));
            }
            set {
                this["Route_Zip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Route_City {
            get {
                return ((string)(this["Route_City"]));
            }
            set {
                this["Route_City"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Route_Street {
            get {
                return ((string)(this["Route_Street"]));
            }
            set {
                this["Route_Street"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Route_Housenumber {
            get {
                return ((string)(this["Route_Housenumber"]));
            }
            set {
                this["Route_Housenumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Route_StartLocation {
            get {
                return ((string)(this["Route_StartLocation"]));
            }
            set {
                this["Route_StartLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ProgramData\\RIS\\Inbox")]
        public string Fax_PathInput {
            get {
                return ((string)(this["Fax_PathInput"]));
            }
            set {
                this["Fax_PathInput"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\ProgramData\\RIS\\Archives")]
        public string Fax_PathArchive {
            get {
                return ((string)(this["Fax_PathArchive"]));
            }
            set {
                this["Fax_PathArchive"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SettingsVersion {
            get {
                return ((int)(this["SettingsVersion"]));
            }
            set {
                this["SettingsVersion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OFF")]
        public global::RIS.Core.DecoderMode Decoder1_Mode {
            get {
                return ((global::RIS.Core.DecoderMode)(this["Decoder1_Mode"]));
            }
            set {
                this["Decoder1_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024, 768")]
        public global::System.Drawing.Point Route_ImageSize {
            get {
                return ((global::System.Drawing.Point)(this["Route_ImageSize"]));
            }
            set {
                this["Route_ImageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Pagers_InsertItem {
            get {
                return ((bool)(this["Pagers_InsertItem"]));
            }
            set {
                this["Pagers_InsertItem"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("OFF")]
        public global::RIS.Core.DecoderMode Decoder2_Mode {
            get {
                return ((global::RIS.Core.DecoderMode)(this["Decoder2_Mode"]));
            }
            set {
                this["Decoder2_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10322")]
        public int Decoder2_Port {
            get {
                return ((int)(this["Decoder2_Port"]));
            }
            set {
                this["Decoder2_Port"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127.0.0.1")]
        public string Decoder2_Server {
            get {
                return ((string)(this["Decoder2_Server"]));
            }
            set {
                this["Decoder2_Server"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color ForegroundColor {
            get {
                return ((global::System.Drawing.Color)(this["ForegroundColor"]));
            }
            set {
                this["ForegroundColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Route_HighQuality {
            get {
                return ((bool)(this["Route_HighQuality"]));
            }
            set {
                this["Route_HighQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Route_ModeTruck {
            get {
                return ((bool)(this["Route_ModeTruck"]));
            }
            set {
                this["Route_ModeTruck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool AppExecute_OnStatus {
            get {
                return ((bool)(this["AppExecute_OnStatus"]));
            }
            set {
                this["AppExecute_OnStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double AlarmData_Width {
            get {
                return ((double)(this["AlarmData_Width"]));
            }
            set {
                this["AlarmData_Width"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Ticker_IsFile {
            get {
                return ((bool)(this["Ticker_IsFile"]));
            }
            set {
                this["Ticker_IsFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("200")]
        public int Ticker_Speed {
            get {
                return ((int)(this["Ticker_Speed"]));
            }
            set {
                this["Ticker_Speed"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Alarmapp_ApiToken {
            get {
                return ((string)(this["Alarmapp_ApiToken"]));
            }
            set {
                this["Alarmapp_ApiToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Alarmapp_OrganisationId {
            get {
                return ((string)(this["Alarmapp_OrganisationId"]));
            }
            set {
                this["Alarmapp_OrganisationId"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.app.ad-sys.de/")]
        public string Alarmapp_WebserviceUrl2 {
            get {
                return ((string)(this["Alarmapp_WebserviceUrl2"]));
            }
            set {
                this["Alarmapp_WebserviceUrl2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024, 768")]
        public global::System.Drawing.Point Warnweather_ImageSize {
            get {
                return ((global::System.Drawing.Point)(this["Warnweather_ImageSize"]));
            }
            set {
                this["Warnweather_ImageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reboot_On {
            get {
                return ((bool)(this["Reboot_On"]));
            }
            set {
                this["Reboot_On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18481006")]
        public string Riverlevel_Messstelle {
            get {
                return ((string)(this["Riverlevel_Messstelle"]));
            }
            set {
                this["Riverlevel_Messstelle"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("HndBayern")]
        public global::RIS.Core.RiverlevelMode Riverlevel_Mode {
            get {
                return ((global::RIS.Core.RiverlevelMode)(this["Riverlevel_Mode"]));
            }
            set {
                this["Riverlevel_Mode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://client-mvc.rescue-information-system.de/")]
        public string Webbrowser_Url {
            get {
                return ((string)(this["Webbrowser_Url"]));
            }
            set {
                this["Webbrowser_Url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Monitor_WeekplanDisabled {
            get {
                return ((bool)(this["Monitor_WeekplanDisabled"]));
            }
            set {
                this["Monitor_WeekplanDisabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1024, 768")]
        public global::System.Drawing.Point Riverlevel_ImageSize {
            get {
                return ((global::System.Drawing.Point)(this["Riverlevel_ImageSize"]));
            }
            set {
                this["Riverlevel_ImageSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("00:00:00")]
        public global::System.TimeSpan Fax_LockTime {
            get {
                return ((global::System.TimeSpan)(this["Fax_LockTime"]));
            }
            set {
                this["Fax_LockTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Fireboard_AuthKey {
            get {
                return ((string)(this["Fireboard_AuthKey"]));
            }
            set {
                this["Fireboard_AuthKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://login.fireboard.net/")]
        public string Fireboard_WebserviceUrl {
            get {
                return ((string)(this["Fireboard_WebserviceUrl"]));
            }
            set {
                this["Fireboard_WebserviceUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Route_ModeFastest {
            get {
                return ((bool)(this["Route_ModeFastest"]));
            }
            set {
                this["Route_ModeFastest"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Route_ModeTraffic {
            get {
                return ((bool)(this["Route_ModeTraffic"]));
            }
            set {
                this["Route_ModeTraffic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"https://maps.dwd.de/geoproxy_warnungen/service?VERSION=1.3.0&REQUEST=GetMap&LAYERS=GRAY_HR_SR_OB_DR,DLM1000_Bundeslaender_Landkreise_gruen,Warnungen_Gemeinden_vereinigt,DLM1000_Landkreise,DLM1000_Gemeinden_Text&STYLES=&CRS=EPSG:3857&BBOX=614360.8293587392,5933210.01991552,1713821.866597408,7423590.537061271&FORMAT=image/png")]
        public string Warnweather_Url {
            get {
                return ((string)(this["Warnweather_Url"]));
            }
            set {
                this["Warnweather_Url"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          {\r\n          \"Monday\": [],\r\n          \"Tuesday\": [],\r\n          \"Wedn" +
            "esday\": [],\r\n          \"Thursday\": [],\r\n          \"Friday\": [],\r\n          \"Satu" +
            "rday\": [],\r\n          \"Sunday\": []\r\n          }\r\n        ")]
        public string Monitor_Weekplan {
            get {
                return ((string)(this["Monitor_Weekplan"]));
            }
            set {
                this["Monitor_Weekplan"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          {\r\n          \"Absender\": null,\r\n          \"Schlagwort\": {\r\n          " +
            "\"Start\": null,\r\n          \"Start_FirstWord\": false,\r\n          \"Stop\": null\r\n   " +
            "       },\r\n          \"Stichwort1\": {\r\n          \"Start\": null,\r\n          \"Start" +
            "_FirstWord\": false,\r\n          \"Stop\": null\r\n          },\r\n          \"Stichwort2" +
            "\": {\r\n          \"Start\": null,\r\n          \"Start_FirstWord\": false,\r\n          \"" +
            "Stop\": null\r\n          },\r\n          \"Stichwort3\": {\r\n          \"Start\": null,\r\n" +
            "          \"Start_FirstWord\": false,\r\n          \"Stop\": null\r\n          },\r\n     " +
            "     \"Ort\": {\r\n          \"Start\": null,\r\n          \"Start_FirstWord\": false,\r\n  " +
            "        \"Stop\": null\r\n          },\r\n          \"Straße\": {\r\n          \"Start\": nu" +
            "ll,\r\n          \"Start_FirstWord\": false,\r\n          \"Stop\": null\r\n          },\r\n" +
            "          \"Hausnummer\": {\r\n          \"Start\": null,\r\n          \"Start_FirstWord\"" +
            ": false,\r\n          \"Stop\": null\r\n          },\r\n          \"KoordinatenHW\": {\r\n  " +
            "        \"Start\": null,\r\n          \"Start_FirstWord\": false,\r\n          \"Stop\": n" +
            "ull\r\n          },\r\n          \"KoordinatenRW\": {\r\n          \"Start\": null,\r\n     " +
            "     \"Start_FirstWord\": false,\r\n          \"Stop\": null\r\n          },\r\n          " +
            "\"Objekt\": {\r\n          \"Start\": null,\r\n          \"Start_FirstWord\": false,\r\n    " +
            "      \"Stop\": null\r\n          },\r\n          \"Station\": {\r\n          \"Start\": nul" +
            "l,\r\n          \"Start_FirstWord\": false,\r\n          \"Stop\": null\r\n          },\r\n " +
            "         \"Kreuzung\": {\r\n          \"Start\": null,\r\n          \"Start_FirstWord\": f" +
            "alse,\r\n          \"Stop\": null\r\n          },\r\n          \"Abschnitt\": {\r\n         " +
            " \"Start\": null,\r\n          \"Start_FirstWord\": false,\r\n          \"Stop\": null\r\n  " +
            "        },\r\n          \"Bemerkung\": {\r\n          \"Start\": null,\r\n          \"Start" +
            "_FirstWord\": false,\r\n          \"Stop\": null\r\n          }\r\n          }\r\n        ")]
        public string Fax_OcrSettings {
            get {
                return ((string)(this["Fax_OcrSettings"]));
            }
            set {
                this["Fax_OcrSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\r\n          {\r\n          \"Status1\": {\r\n          \"MainOn\": true,\r\n          \"Alar" +
            "mOn\": true,\r\n          \"Color\": \"#FF00FF00\"\r\n          },\r\n          \"Status2\": " +
            "{\r\n          \"MainOn\": true,\r\n          \"AlarmOn\": true,\r\n          \"Color\": \"#F" +
            "F008000\"\r\n          },\r\n          \"Status3\": {\r\n          \"MainOn\": true,\r\n     " +
            "     \"AlarmOn\": true,\r\n          \"Color\": \"#FFFFA500\"\r\n          },\r\n          \"" +
            "Status4\": {\r\n          \"MainOn\": true,\r\n          \"AlarmOn\": true,\r\n          \"C" +
            "olor\": \"#FFFF0000\"\r\n          },\r\n          \"Status5\": {\r\n          \"MainOn\": fa" +
            "lse,\r\n          \"AlarmOn\": false,\r\n          \"Color\": \"#00FFFFFF\"\r\n          },\r" +
            "\n          \"Status6\": {\r\n          \"MainOn\": true,\r\n          \"AlarmOn\": true,\r\n" +
            "          \"Color\": \"#FF808080\"\r\n          },\r\n          \"Status7\": {\r\n          " +
            "\"MainOn\": false,\r\n          \"AlarmOn\": false,\r\n          \"Color\": \"#00FFFFFF\"\r\n " +
            "         },\r\n          \"Status8\": {\r\n          \"MainOn\": false,\r\n          \"Alar" +
            "mOn\": false,\r\n          \"Color\": \"#00FFFFFF\"\r\n          },\r\n          \"Status9\":" +
            " {\r\n          \"MainOn\": false,\r\n          \"AlarmOn\": false,\r\n          \"Color\": " +
            "\"#00FFFFFF\"\r\n          },\r\n          \"StatusA\": {\r\n          \"MainOn\": false,\r\n " +
            "         \"AlarmOn\": false,\r\n          \"Color\": \"#00FFFFFF\"\r\n          },\r\n      " +
            "    \"StatusC\": {\r\n          \"MainOn\": true,\r\n          \"AlarmOn\": true,\r\n       " +
            "   \"Color\": \"#FFFFFFFF\"\r\n          },\r\n          \"StatusE\": {\r\n          \"MainOn" +
            "\": false,\r\n          \"AlarmOn\": false,\r\n          \"Color\": \"#00FFFFFF\"\r\n        " +
            "  },\r\n          \"StatusF\": {\r\n          \"MainOn\": false,\r\n          \"AlarmOn\": f" +
            "alse,\r\n          \"Color\": \"#00FFFFFF\"\r\n          },\r\n          \"StatusH\": {\r\n   " +
            "       \"MainOn\": false,\r\n          \"AlarmOn\": false,\r\n          \"Color\": \"#00FFF" +
            "FFF\"\r\n          },\r\n          \"StatusJ\": {\r\n          \"MainOn\": false,\r\n        " +
            "  \"AlarmOn\": false,\r\n          \"Color\": \"#00FFFFFF\"\r\n          },\r\n          \"St" +
            "atusL\": {\r\n          \"MainOn\": false,\r\n          \"AlarmOn\": false,\r\n          \"C" +
            "olor\": \"#00FFFFFF\"\r\n          },\r\n          \"StatusP\": {\r\n          \"MainOn\": fa" +
            "lse,\r\n          \"AlarmOn\": false,\r\n          \"Color\": \"#00FFFFFF\"\r\n          },\r" +
            "\n          \"StatusU\": {\r\n          \"MainOn\": false,\r\n          \"AlarmOn\": false," +
            "\r\n          \"Color\": \"#00FFFFFF\"\r\n          }\r\n          }\r\n        ")]
        public string FmsSettings {
            get {
                return ((string)(this["FmsSettings"]));
            }
            set {
                this["FmsSettings"] = value;
            }
        }
    }
}
