// <auto-generated />
namespace RIS.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V7_5_0 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V7_5_0));
        
        string IMigrationMetadata.Id
        {
            get { return "202007310819497_V7_5_0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
